let myjoke = [`Why did the scarecrow win an award? Because he was outstanding in his field.`,
    `Why did the melon jump into the lake? It wanted to be a water-melon.`,
    `What did the duck say when it bought lipstick? “Put it on my bill.”`,
    `What do you call a pig that does karate?&nbsp;A pork chop.`,
    `What has a bed that you can’t sleep in? A river.`,
    `Why were the teacher’s eyes crossed? She couldn’t control her pupils.`,
    `What starts with E, ends with E, and has only 1 letter in it? An Envelope.`,
    `How does the ocean say hello? It waves.`,
    `What lights up a soccer stadium? A soccer match.`,
    `What creature is smarter than a talking parrot? A spelling bee.`,
    `Which U.S. state has the smallest soft drinks? Minnesota (as in, “mini-soda”).`,
    `Why couldn’t the leopard play hide and seek?&nbsp;Because he was always spotted.`,
    `Apparently, you can’t use “beef stew” as a password. It’s not stroganoff.`,
    `Why did the drum take a nap? It was beat.`,
    `Where do hamburgers go dancing?&nbsp; They go to the meat-ball.`,
    `Why did the tomato turn red?&nbsp; It saw the salad dressing.`,
    `Why shouldn’t you write with a broken pencil? Because it’s pointless.`,
    `What do you call two monkeys that share an Amazon account? Prime mates.`,
    `Why are teddy bears never hungry? Because they’re always stuffed!`,
    `Why did the tree go to the dentist? It needed a root canal.`,
    `If athletes get athlete’s foot, what do elves get? Mistle-toes.`,
    `Why couldn’t the pony sing? Because she was a little hoarse.`,
    `Where do cows go for entertainment? The mooooo-vies!`,
    `What do you call a pig that does karate? A pork chop.`,
    `How does NASA organize a party? They planet.`,
    `Why did Adele cross the road?&nbsp;&nbsp;To sing, “Hello from the other side!`,
    `What runs around a yard without actually moving? A fence.`,
    `What’s an astronaut’s favorite candy? A Mars bar.`,
    `Where do sheep go to get their hair cut?&nbsp; The baa-baa shop.`,
    `Why are there gates around cemeteries? Because people are dying to get in.`,
    `What do you get when you cross a snake with a pie? A pie-thon!`,
    `Why is Peter Pan always flying? He neverlands.`,
    `What’s the most musical part of the chicken? The drumstick.`,
    `Why do seagulls fly over the sea? Because if they flew over a bay, they would be bagels.`,
    `How do you know when the moon has had enough to eat? When it’s full.`,
    `What kind of music do planets like? Neptunes.`,
    `Why can’t you trust an atom?&nbsp;Because they make up everything.`,
    `What do you call a group of disorganized cats? A cat-tastrophe.`,
    `Why do bees have sticky hair? Because they use honeycombs.`,
    `Where do you learn to make banana splits? At sundae school.`,
    `How do you tell if a vampire is sick? By how much he is coffin.`,
    `Why are ghosts good cheerleaders?&nbsp;&nbsp;Because they have a lot of spirit!`,
    `What happens to a frog’s car when it breaks down? It gets toad away.`,
    `Why did the witches’ team lose the baseball game?&nbsp;&nbsp;Their bats flew away.`,
    `Why did the school kids eat their homework?&nbsp;Because their teacher told them it was a piece of cake.`,
    `Why are hairdressers never late for work?&nbsp;&nbsp;Because they know all the short cuts!`,
    `What is the difference between a teacher and a train?&nbsp;One says, “Spit out your gum,” and the other says`, `“Choo choo choo!”`,
    `Why does Humpty Dumpty love autumn?&nbsp;&nbsp;Because Humpty Dumpty had a great fall.`,
    `How do you make a tissue dance?&nbsp;Put a little boogie in it.`,
    `What is the tallest building in the entire world?&nbsp;&nbsp;The library, because it has so many stories.`,
    `How do trees access the internet?&nbsp;They log in.`,
    `What do you get when you cross a fish and an elephant?&nbsp; Swimming trunks.`,
    `Why did the painting go to jail?&nbsp;&nbsp;It was framed.`,
    `Why did Cinderella get kicked off the soccer team?&nbsp;Because she ran away from the ball.`,
    `Why do we tell actors to break a leg?&nbsp; Because every play has a cast.`,
    `Helvetica and Times New Roman walk into a bar. The bartender says, “We don’t serve your type.”`,
    `Why wouldn’t the shrimp share his treasure? Because he was a little shellfish.`,
    `Why should you knock on the refrigerator before opening the door? In case there is a salad dressing`,
    `When is a door not a door? When it is ajar`,
    `What’s the smartest insect?    A spelling bee!    `,
    `How does the ocean say hi?     It waves!   `,
    `Name the kind of tree you can hold in your hand?   A palm tree!  `,
    `Where did the music teacher leave her keys?    In the piano!  `,
    `Why do birds fly south in the winter?  It’s faster than walking!    `,
    `Which superhero hits home runs?    Batman!    `,
    `Why did the bird get in trouble at school?     For tweeting on a test! `,
    `Why is a football stadium always cold?  It has lots of fans!    `,
    `Why did the chicken cross the playground?  To get to the other slide?   `,
    `What kind of math do birds love?   Owl-gebra!    `,
    `How does a barber drive to work?    He takes shortcuts!   `,
    `What kind of shoes do frogs love?  Open-toad!   `,
    `Why do ducks always pay with cash?     Because they always have bills! `,
    `Where do most horses live?     In neigh-borhoods!  `,
    `Which planet loves to sing?    Nep-tune!  `,
    `Why are basketball courts always wet?  Because the players dribble! `,
    `What kind of keys are sweet?   Cookies!  `,
    `Knock, knock!\n    Who’s there?    \nWoo.\n    Woo-hoo!    \nNo need to get so excited; it’s just a joke!`,
    `What do you call cheese that belongs to someone else?  Nacho cheese!    `,
    `Why did the peanut get into a rocket?  He wanted to be an astro-nut!    `,
    `What fruit do twins love?  Pears!   `,
    `How do bees brush their hair?  With honeycombs! `,
    `Why won’t peanut butter tell you a secret?     He’s afraid you’ll spread it!   `,
    `Who eats snails?   People who don’t like fast food!  `,
    `Why did the banana visit the doctor?   He wasn’t peeling well!   `,
    `Why did the computer get sick?     It caught a virus!  `,
    `Why did the teacher have birdseed?     For her parrot-teacher conference!  `,
    `Why are elephants to wrinkly?  Have you ever tried to iron one? `,
    `Why was the broom late to school?  It over-swept!   `,
    `What is the strongest animal in the sea?   Mussels!  `,
    `What kind of chicken is the funniest?  A comedi-hen!    `,
    `What do you call a seagull that lives by the bay?  A bagel! `,
    `What color do cats prefer?     Purr-ple    `,
    `What does a triceratops sit on?    Its tricera-bottom!    `,
    `What is a sleeping dinosaur?   A dino-snore! `,
    `What kind of pizza do dogs eat?    Pup-eroni pizza!   `,
    `How do you help a baby astronaut fall asleep?  You rock-et! `,
    `If cars run on gas, what do cats run on?   Their paws!   `,
    `What do cats wear to bed?  Paw-jamas!   `,
    `What kind of pictures do turtles take?     Shell-fies! `,
    `What do you call a famous turtle?  A shell-ebrity!  `,
    `What do you feed an alligator?     Anything it wants!  `,
    `What makes a sick lemon feel better?   Lemon-aid!    `,
    `How does Spiderman do research?    On the World Wide Web! `,
    `What’s the largest gem on earth?   A baseball diamond!   `,
    `What do you get if you dip a cat in chocolate?     A Kitty-Kat Bar!    `,
    `What food is never on time?    Choco-late!    `,
    `What cookie flavor do monkeys love?    Chocolate Chimp!   `,
    `Why do hurricanes wear a monocle to see?   Because they have one eye!    `,
    `What did the clock ask the watch?  Hour you doing?  `,
    `What’s the most famous fish?   A starfish!   `,
    `Why don’t oysters share?   They’re shell-fish!   `,
    `Why are fish so intelligent?   Because they live in schools! `,
    `What kind of fish loves going to battle?   A swordfish!  `,
    `Where do birds invest their money?     The stork-market!   `,
    `What nut has the most money?   A cashew! `,
    `What do you call a cow who plays the trumpet?  A moo-sician!    `,
    `What’s a pirate’s favorite county?     Arrrrgh-entina! `,
    `Why can’t Dalmatians win at hide and seek?     Because they’re always spotted! `,
    `What do newborn kittens wear?  Dia-purrs!   `,
    `What did the little tree say to the big tree?  Leaf me alone!   `,
    `Knock, knock!\n    Who’s there?    \nTank.\n    Tank who?   \nYou’re welcome!`,
    `What’s in the recipe for gold soup?    Fourteen carrots!  `,
    `Name Spiderman’s favorite month?   Web-ruary!    `,
    `Knock, knock!\n    Who’s there?    \nPizza.\n    Pizza who?  \nPizza on earth, good will to men!`,
    `What’s an astronaut’s favorite meal?   Launch!   `,
    `Why can’t noses be 12 inches long?     They’d be a foot!   `,
    `What does it sound like when a nut sneezes?     Ca-shew!   `,
    `Where do smart burgers sit?     On honor rolls!    `,
    `Which holiday do cows enjoy most?  Moo-Year’s Day   !`,
    `Why can’t bicycles stand on on their own?  They’re two-tired!   `,
    `Where do you go to school to learn how to greet people?    Hi school! `,
    `What do cheerleaders eat for breakfast?    Cheerios!  `,
    `Knock, knock!\n    Who’s there?    \nAnita?\n    Anita who?  \nAnita borrow a pencil!`,
    `How do ice hockey players stay cool?   They sit next to the fans!    `,
    `What’s the hardest part about learning to skydive?  The ground! `,
    `Why did the piano teacher need a ladder?   To reach the high notes!  `,
    `What kind of fishing bait do librarians use?   Book-worms!   `,
    `Knock, knock!\n    Who’s there?    \nLettuce.\n    Lettuce who?    \nLettuce in and we’ll tell you!`,
    `Which state is the smartest?    Alabama—it has four As and one B! `,
    `What state does the most writing?  Pennsylvania!    `,
    `Which country is fastest?  Russia!  `,
    `Why was the math book crying?  It had lots of problems! `,
    `What’s a math teacher’s favorite season?   Sum-mer!  `,
    `What kind of lights did Noah have on the ark?   Flood-lights!    `,
    `What is the center of gravity?  The letter V!   `,
    `What goes up and never comes down?     Your age!   `,
    `Knock, knock!\n    Who’s there?    \nPolice.\n    Police who? \nPolice let us in! It’s cold out here!`,
    `What starts with P and ends with E and has thousands of letters?   Post office!  `,
    `What breaks when you speak?    Silence!   `,
    `What do attorneys wear to court?   Law-suits!    `,
    `Why did the doctor get mad?    He ran out of patients!    `,
    `What notes do pirates love to sing?    The high Cs!   `,
    `What gets more wet the more it dries?  A towel! `,
    `How are dogs like cell phones?     They both have collar id.   `,
    `Why do you go to bed at night?     Because the bed won’t go to you!    `,
    `Which month do trees dislike?  Sep-timber!  `,
    `Knock, knock!\n    Who’s there?    \nFigs.\n    Figs who?   \nFigs the doorbell! It’s broken!`,
    `Why are ducks good at basketball?  They make fowl shots!    `,
    `What kind of dog always knows the time?    A watch-dog!  `
]

let hindi = [
    "निराशा, एक ऐसी बीमारी है जिसकी चपेट में एक बार कोई आ गया तो उसका उभरना बहुत ही मुश्किल हो जाता है. हसना स्वास्थ्य के लिए बेहद फायदेमंद होता है. अगर आप सुबह : शाम हंसने की आदत डाल लें तो कोई भी बीमारी, चाहे मानसिक हो या शारीरिक आपके पास भी नहीं आएगी. आज हम आपके साथ शेअर कर रहे हैं मजेदार जोक्स Funny Jokes in Hindi जो आपको खूब हंसाएंगे.",
    "माँ  :  बेटा क्या कर रहे हो? <br>  बेटा  :  पढ़ रहा हु माँ.. <br>   माँ  :  शाबाश! क्या पढ़ रहे हो? <br>    बेटा  :  आपकी होने वाली बहु के SMS. <br> दे थप्पड़, दे थप्पड़!",
    "पति और पत्नी का ज़ोरदार झगड़ा होता है. <br>  पति गुस्से से :  तेरी जैसी 50 मिलेंगी.  <br>   पत्नी हंसके :  अभी भी मेरी जैसी ही चाहिए!",
    "लड़की वाले बेटी के लिए लड़का देखने गए, <br>  लड़की वाले :  कितना कमा लेते हो? <br>   लड़का :  इस महीने दो करोड़ कमाया.   <br>    लड़की वाले :  फिर क्या हुआ?  <br>   लड़का :  बस, फिर मोबाइल में तीन पत्ती हेंग हो गया,    <br>   और सारी कमाई चली गयी.",
    "उसने मुझसे पूछा <br>  चाहोगे मुझे कब तक,    <br>   मैंने भी मुस्कुराके कह दिया,   <br> मेरी बीवी. <br>    को न पता चले तब तक.",
    "टीचर : मैं दो वाक्य दूंगा उसमें आपको अंतर बताना है.    <br>  पहला वाक्य :  उसने बर्तन धोए.   <br>    दूसरा वाक्य :  उसे बर्तन धोने पड़े.    <br>   पप्पू : पहले वाक्य में कर्ता अविवाहित है.    <br> और दूसरे वाक्य में कर्ता विवाहित है.",
    "लड़का :  मैं आपकी बेटी से शादी करना चाहता हूं,  <br>  लड़की का बाप :  कितना कमा लेते हो.    <br>  लड़का :  १९००० हजार महीना. <br>    लड़की का बाप :  १५००० मै अपनी बेटी को पाकेट मनी देता हूं.  <br> लड़का :  वो मिलाके के ही बोल रहा हूं अंकल.",
    "पत्नी  :  हमेशा मेरा आधा माथा दुखता है,  <br>  लगता है डॉक्टर को दिखाना पड़ेगा..    <br>  पति  :  अरे उसमे डॉक्टर को क्या बताना ! <br>    वो तो जितना है उतना दुखेगा ही. <br> बस तब से ही पति का पूरा बदन दुःख रहा है.",
    "पति अपनी पत्नी से : :  मेरी शर्ट को उल्टी करके प्रेस करना.  <br>  पत्नी : :  ठीक है   <br>  कुछ देर बाद   <br> पति : :  मेरी शर्ट को प्रेस कर दिया क्या    <br>    पत्नी : :  नहीं अभी नहीं <br>  पति : :  क्यों.?   <br>   पत्नी : :  अभी मुझे उल्टी ही नही आ रही तो उल्टी करके कैसे प्रेस करूँ.    <br>  पति बेहोश.",
    "फादर: अगर इस बार तुम इम्तिहान मे फैल हुए तो, <br>  मुझे पापा मत कहना.    <br>   इम्तिहान के बाद, <br> फादर: How is Your Result? <br>  सन: दिमाग का दही मत कर   <br>   बाबूलाल तु बाप कहलाने का हक खो चूका है.",
    "एक सरकारी दफ्तर के <br>  बोर्ड पार लिखा था, <br>   कृपया शोर ना करे. <br>    किसी ने उसके नीचे  <br> लिख दिया,    <br> “वरना हम जाग जायेंगे..”",
    "डॉक्टर ने आदमी से पुछा,   <br>  क्या आप का और आपकी बीवी का खून एक ही है? <br> आदमी ने कहा,    <br>  क्यों नही? ज़रूर होगा! पचास  <br>    साल से मेरा ही खून जो पी रही है.",
    "पति : अल्लाह ने तुम्हें 2 आँखे दी हैं,  <br>  चावल से पत्थर नही निकाल सकती?    <br>  पत्नी : अल्लाह ने तुम्हे 32 दांत दिए है,    <br>    2 : 4 पत्थर नही चबा सकते?",
    "अर्ज है: रोज रोज वजन   <br>  नापकर क्या करना है, <br> एक दिन तो सबने मरना है,   <br>  चार दिन की है जिंदगी, <br> खा लो जी भर के,  <br>  अगला जन्म फिर ३ किलो से <br>  शुरू करना है !",
    "थप्पड मारने पर नाराज वाईफ    <br>  से हसबंड बोला:  <br>    “आदमी उसी को मारता है जिससे वो प्यार करता है.” <br>    वाईफ ने हसबंड को 2 थप्पड मारे और    <br> बोली “आप क्या समझते है मै आपसे प्यार नही करती”",
    "वाईफ: प्लीज बाइक तेज ना चलाओ, <br>  मुझे डर लग रहा है.   <br>   सरदार: अगर तुझे भी डर लग रहा है, <br>  तो मेरी तरह आँखें बंद कर ले.",
    "पत्नी: डॉक्टर साहब..    <br>  मेरे पती को रात मे बडबडाने की आदत है, <br>    कोई उपाय बताये?  <br> डॉक्टर: आप उन्हें दिन मे <br> बोलने का मौका दिया करे..",
    "पापा बेटी से: :   <br>  बेटी पहले तो तुम मुझे पापा कहती थी,  <br>  लेकिन अब तुम मुझे डैड कहती हो, क्यों?    <br>  बेटी: :  ओह डैड, पापा कहने से लिपस्टिक खराब होती है.",
    "संता बार मे रो रहा था.    <br>  बंता: क्यों रो रहे हो?  <br>    संता: और क्या करू? <br>    जिस लडकी को भुलाना चाहता हूँ,  <br> उसका नाम ही याद नही आता.",
    "पत्नी ने गुस्से में पति से कहा:   <br>  मैं तंग आ गई हूँ रोज की किच : किच से.. <br> मुझे तलाक चाहीये!  <br>  पति: ये लो चॉकलेट खाओ.. <br>  पत्नी (रोमांटिक होते हुए):    <br>   मना रहें हो मुझे..    <br> पति: नहीं रे पगली, माँ कहती है,  <br>   अच्छा काम करने से पहले, <br>   मीठा खाना चाहिए.",
    "इंग्लिश ग्रामर की टीचर :  आज हम नाउन पढ़ेंगे <br>  टीचर :  लड़की सबसे हंस के बात करती है,  <br>   इसमें लड़की क्या है? <br>   पप्पू :  मैडम जी वो लड़की बिगड़ी हुई है,   <br>    किसी लड़के के चक्कर में पड़ी है.",
    "पति बाल कटवाकर घर आया. <br>  पति: देखो, मैं तुमसे दस साल छोटा लगता हूं कि नहीं?   <br>   पत्नी: मुंडन करवा लेते तो लगता जैसे अभी पैदा हुए हो.",
    "पप्पू: पापा बुलेट दिला दो,  <br>  बाप: पड़ोसन की लड़की को  <br>  देख बस से जाती है..    <br>  पप्पू: यही तो देखा नहीं जाता !",
    "पप्पू अपनी पत्नी से :  <br>  अच्छा ये बताओ ‘बिदाई’ के समय तुम <br>   लड़कियां इतनी रोती क्यों हो?    <br>    पत्नी :  ‘पागल’ अगर तुझे पता चले..   <br>  अपने घर से दूर ले जाकर कोई तुमसे   <br> ‘बर्तन मंजवाएगा’ तो तू क्या नाचेगा.",
    "मेरे एक पड़ोशी है, जिनका नाम है ‘भगवान’   <br>  और उनकी लड़की का नाम है भक्ति, <br> मम्मी बोलती है कि, <br>  ‘बेटा भगवान की भक्ति में मन लगाया कर’  <br>   अब मम्मी को कैसे समझाऊ की    <br>   भक्ति में तो मन लगाता हुँ, पर    <br> भगवान नहीं मान रहे.",
    "इस मतलबी दुनिया में, <br>  एक पान वाला ही है,    <br>   जो पूछ कर चुना लगाता है !",
    "पप्पू की वाईफ रोमांटिक मूड मे थी  <br>  पूरे बैड पर बाँहे फैला कर लेट गयी,  <br>  और पप्पू से बोली कुछ समझे?   <br>  पप्पू :  समझ गया आज तू पूरे बैड पर सोना चाहती है न डायन.",
    "हरियाणवी लड़की: पासपोर्ट साइज फोटो खींच दे.  <br>  और उसमें मेरी नई चप्पल भी आनी चाहिए    <br>  फोटोग्राफर भी हरियाणवी था.   <br>    बोल्या टट्टी वाली स्टाइल में बैठ जा.",
    "अपने ससुर जी की दुलारी हूँ मैं,   <br>  अपने Hubby की भी प्यारी हूँ मैं, <br> फिलहाल तो ये सब सपना है,   <br>  क्यों की अभी तक कुवारी हूँ मैं !",
    "अगर आपका बेटा “Hello Hello” करते हुए,   <br>  रूम से बाहर निकल जाए,   <br> तो समझ जाना की,    <br>    आपकी होने वाली बहु का फ़ोन है !",
    "LKG के बच्चे के पेपर मे 0 आया.    <br>  गुस्से से पिता: यह क्या है?  <br>    बच्चा: पिताजी, शिक्षक के पास स्टार खत्म हो हो गए थे  <br>    इसलिये उसने मून दे दिया.",
    "कुछ दोस्त ऐसे हैं जो घर से <br>  बीवी की लात खाकर आते हैं और. <br>   दोस्तों से कहते फिरते हैं  <br>    आज तो मैं लेग पीस खाकर आया हूं.",
    "डेट पर लड़के ने लड़की से कहा,  <br>  जानू, एक बात कहना चाहता हूं!  <br>  लड़की: क्या?  <br>  लड़का: मेरी पहले से एक गर्लफ्रेंड है!    <br>  लड़की: डरा दिया साले, मुझे लगा कि पैसा नहीं है!",
    "पति: अरे सुनो, मुन्ना रो रहा है चुप कराओ इसे.   <br>  पत्नी (गुस्से में): मैं काम करूं या बच्चे संभालू,    <br> मैं इसे दहेज में नहीं लाई थी, खुद ही चुप करा लो.   <br>   पति: फिर रोने दे… मैं कौन सा इसे बारात में लेकर गया था.",
    "शादीशुदा महिला :  पंडितजी, मेरे पति हमेशा मुझसे लड़ते रहते हैं.   <br>  घर की सुख : शांति के लिए कौन : सा व्रत रखूं?   <br> पंडितजी :  मौन व्रत रखो बेटा, सब बढ़िया होगा!",
    "एक पार्टी में एक सुन्दर सी लड़की एक लड़के के पास गई, <br>  लड़की: सुनिए, मेरे एक हाथ में गिलास और दूसरे में प्लेट है, <br>   आप मेरे चेहरे से एक चीज़ हटा देंगे! <br>    लड़का: हाँ हाँ क्यों नहीं, क्या चीज़ हटानी है? <br> लड़की: अपनी कुत्ते जैसी नज़र!",
    "सन: मॉम, पापा बहुत शरीफ है,  <br>  मॉम: वो कैसे बेटा,  <br>  सन: पापा जब भी किसी लडकी को देखते है,   <br>  तो अपनी एक आँख बंद कर लेते है.",
    "बहु के 1 : 2 अफेयर सुनकर <br>  पती ने जान दे दी, <br>   3 : 4 अफेयर सुनकर ससुर ने जान दे दी,  <br>    लेकिन सास चुप रही क्यों?  <br>    क्युकी सास भी कभी बहु थी.",
    "आदित्य अपनी गर्लफ्रेंड के पिता से मिलने गया, <br>  लड़की का पिता: मैं नहीं चाहता कि मेरी बेटी   <br>   अपनी पूरी जिंदगी एक मूर्ख इंसान के साथ गुज़ारे.    <br>  आदित्य: बस अंकल, इसीलिए तो मैं उसे यहां से ले जाने आया हूँ.   <br>    दे जूते.. दे चप्पल !",
    "वाईफ TV पर मॅच देख रही थी,  <br>  हसबंड स्मार्ट बनके आया और बोला,   <br>  “डार्लिंग मै कैसा लग रहा हुँ?” तभी वाईफ जोरसे चिल्लाई,  <br> छक्का!",
    "गारमेंट शॉप में  <br>  लड़की:अंडरवियर दिखाना प्लीज़.   <br>  सरदार थोड़ा शरमाकर: जी आज नहीं पेहनी.",
    "रुपेश : पापा मुझे एक लड़की पसंद है,  <br>  मैं उससे शादी करना चाहता हूँ..  <br>  पापा: क्या वो भी तुझे पसन्द करती है? <br>  रुपेश : हाँ जी हाँ..    <br>   पापा: जिस लड़की की पसन्द ऐसी हो  <br> मैं उसे अपनी बहू नहीं बना सकता.",
    "सरदार दुखी था. <br>  किसी ने पुछा: क्यों टेंशन मे हो? <br>   सरदार: यार एक दोस्त को प्लास्टिक सर्जरी के लिए 2 लाख दिए,   <br>    अब साले को पहचान नहीं पा रहा हुँ.",
    "संता अपनी बीमारी की वजह से डॉक्टर के पास गया,   <br>  डॉक्टर: आपकी बीमारी की सही वजह मेरी समझ में नहीं आ रही,   <br> हो सकता है दारु पीने की वजह से ऐसा हो रहा हो,   <br>    संता: कोई बात नहीं डॉक्टर साहब, <br>   जब आपकी उतर जाएगी तो मैं दोबारा आ जाऊंगा.",
    "पापा और 15 साल का बेटा एक होटल में गए,  <br>  पापा  :  वेटर एक बियर और एक आईसक्रीम लाओ,  <br>  बेटा  :  आईसक्रीम क्यों पापा, आप भी बियर लीजिये ना,    <br>  दे.. चप्पल.. पे.. चप्पल!",
    "पत्नी : कुछ साल पहले मेरा फिगर पेप्सी की बोतल की तरह था,  <br>  पति : वो तो अब भी है बस,   <br>  पहले बोतल 300ML की थी अब 2 लीटर की है.",
    "बाप: मेरे 4 बच्चे है,    <br>  पहिला MBA,    <br>    दूसरा MCA,    <br>  तीसरा PHD,    <br>    चौथा चोर है.    <br>  फ्रेंड: चोर को घर से निकालते क्यू नहीं?  <br>    बाप: वही तो कमाता है, बाकी सब बेरोज़गार है.",
    "संता  :  यार मुन्नू, पत्नी को बेगम क्यों कहा जाता है? <br>  बंता  :  क्या है की शादी के बाद, <br>   सारे गम पति के हो जाते है.   <br>    तो पत्नी बेगम हो जाती है.",
    "मनोहर: क्या एक वाईफ अपने हसबंड को लखपती बना सकती है?  <br>  गजोधर: हा, पर हसबंड करोडपती होना चाहिए.",
    "बुढ़िया का दामाद बहुत काला था,    <br>  सास: दामाद जी आप तो 1 महीना यहाँ रुको, <br>    दूध, दही खाओ मौज करो, आराम से रहो यहाँ,    <br> दामाद: अरे वाह सासु माँ आज तो बड़ा प्यार आ रहा है मुझ पे,    <br>   सास: अरे प्यार व्यार कुछ नहीं कलमुहे,  <br> वो हमारी भैंस का बच्चा मर गया है,   <br> कम से कम तुम्हे देख कर दूध तो देती रहेगी.",
    "घर समय से पहुँचो,  <br>  तो खाना गर्म और   <br>  घरवाली ठंडी मिलेगी.   <br> और देर से पहुँचो,   <br>    तो खाना ठंडा और घरवाली गर्म!",
    "संता: पापा आज मेरी गर्लफ्रेंड का बर्थडे है, उसे क्या दू? <br>  पापा: दिखने मे कैसी है?  <br>   संता: मस्त है.    <br>   पापा: मेरा मोबाइल नंबर दे दे!",
    "गर्ल: क्या कर रहे हो?   <br>  बॉय: मक्खियाँ मार रहा हुँ,  <br> गर्ल: कितनी मारी?  <br> बॉय: 3 मेल और 2 फीमेल,    <br> गर्ल: कैसे मालुम?    <br>   बॉय: क्योंकि,    <br> 3 दारू की बोतल से चिपकी थी और 2 फ़ोन से.",
    "वाह प्रभु, अजब तेरी लीला है,   <br>  चूहा बिल्ली से डरता है,    <br> बिल्ली कुत्ते से डरती है,    <br>   कुत्ता आदमी से डरता है,    <br> आदमी बीवी से डरता है  <br>   और बीवी चूहे से डरती है.",
    "माँ: सो जा वरना गब्बर आ जायेगा, <br>  बच्चा: पहले 100 रुपए दे दो,    <br>   माँ: क्यों?  <br> बच्चा: वरना मै पापा को बता दूंगा <br> की रोज रात को यहाँ गब्बर आता है.",
    "पति रोज किचन में जाता और चीनी का डिब्बा खोलकर देखता    <br>  और फिर बंद करके रख देता, <br>    पत्नी: रोज रोज ये क्या करते रहते हो?   <br> पति: चुप कर, डॉक्टर ने कहा है,    <br>    रोज अपनी शुगर चेक करते रहो.",
    "संजू: पापा मुझे स्कुल छोड़ने  <br>  आप क्यों आते हो?   <br>  मेरे सभी दोस्तों को छोड़ने तो  <br> उनकी मम्मी आती है, <br> पापा: बस इसीलिए बेटा.",
    "India के आधे अमीर जादे अपने  <br>  बाप को नहीं जानते.. <br>  They Just keep Asking Other, <br>   “तु जानता है मेरा बाप कौन है?”",
    "पति पत्नी मंदिर मे पूजा करने गये,    <br>  पति: तुमने क्या माँगा?  <br>    पत्नी: कि आप और मैं सात जन्म तक साथ रहें    <br>    और तुमने क्या माँगा?   <br>  पति: भगवान करे ये मेरा सातवाँ जन्म हो.",
    "एक बार पति की तबियत बहुत ख़राब थी, <br>  पति : काम वाली शांति को बुलाओ, <br>   पत्नी : क्यों?    <br>    पति : डॉक्टर ने कहा है कि दवा खाकर शांति के साथ सो जाना.",
    "हर आदमी का सपना   <br>  ७ अंको में सॅलरी <br> ६ अंको में बचत   <br>  ५ बेडरूम वाला घर   <br> ४ पहियों की गाड़ी <br>    ३ हप्ते की छुट्टिया <br> २ प्यारे बच्चे    <br>  १ गूंगी बीवी.",
    "एक लड़का, लड़की देखने गया,    <br>  बहुत देर से सूसू रोक के रखे हुए था,   <br>    बाद में लड़की से बोला, <br>   सूसू करने की जगह दिखाओ,    <br>    लड़की (शरमाकर): नहीं,    <br>  पहले आप दिखाओ.",
    "मुर्गी : एक अंडा देना,    <br>  शॉपकीपर : अंडा तो तुम देती हो    <br>    मुर्गी : हा पर मेरे पती ने कहा है <br>  की ४ रु के लिए क्यों अपना    <br>   फिगर खराब कर रही हो !",
    "जब घर में बच्चा पैदा होता है,   <br>  माँ  :  इसकी नाक तो मुझ पर गयी है,   <br> बाप  :  इसकी आँखे मुझ पर गयी है,    <br>    चाचा  :  इसके बाल मुझ पर गए है, <br>  मां  :  इसकी स्माइल मुझ पर गयी है, <br>   और वही बच्चा जवान होकर जब लड़की छेड़ता है,  <br>    तो सब बोलते है,   <br>    पता नहीं हरामखोर किस पर गया है.",
    "पापा: नालायक इतनी रात को कहाँ से आ रहा है? <br>  भोलू: अपनी गर्लफ्रेंड से मिलने गया था.   <br>   पापा: किस लिए? <br>  भोलू: हाँ पापा, 7 : 8 तो किस ले ही लिए.",
    "आज कुछ घबराये से लगते हो,    <br>  ठंड मे कपकपाये से लगते हो, <br>    निखर कर आई है सुरत आपकी, <br> बहुत दिनों बाद नहाये से लगते हो.",
    "अगर आपका दोस्त    <br>  Online रहने के बाद भी   <br>    आपको Reply नहीं दे रहा, <br>   तो समझ लीजिये की, <br>    अब वो Single नहीं रहा.",
    "ससुर ने दामाद से कहा: 6 साल मे 8 बच्चे.. ये क्या है? <br>  दामाद: मैने आपसे कहा था गरीब जरूर हु,  <br>   पर आपकी बेटी को कभी खाली पेट नही रखूँगा !",
    "एक दिन संता अपनी भाभी को पिट रहा था, <br>  राह चलते लोगो ने पूछा क्यो मार रहे हो इस बेचारी को?  <br>   संता बोला: मेरी भाभी अच्छी औरत नही है,    <br>   लोगो ने पूछा: क्यों क्या हुवा?  <br> संता बोला: यार मेरे सभी दोस्त मोबाइल पर लगे रहते है, <br> और जिसे भी पुछू तुम लोग किस से बात कर रहे हो?    <br>  तो सब बोलते है तेरे भाभी से.",
    "पति अपनी नाराज पत्नी को रोज    <br>  फ़ोन करता है..  <br>    सासूजी: कितनी बार कहा की वो    <br>    अब तुम्हारे घर नहीं आएगी,  <br>  फिर क्यों रोज रोज फ़ोन करते हो? <br>  जमाई : सुन कर अच्छा लगता है इसीलिए.",
    "सिर्फ मार्क जुकरबर्ग ही दुनिया का ऐसा अकेला इंसान है..  <br>  जिसकी मां बोलती है,  <br>  बेटा टाइम : पास छोड़, Facebook और Whatsapp पर ध्यान दे.",
    "पापा: बेटा तुम पास हो या ना हो मैं तुम्हें बाइक जरूर दिला दूंगा.. <br>  पप्पू: थैंक्यू पापा जी,   <br>   पापा: अगर पास हुये तो ‘हीरो होन्डा’ कॉलेज जाने के लिये,  <br>  अगर फेल हुये तो ‘राजदूत’ दूध बेचने के लिये.",
    "जरुरी नहीं की कुत्ता ही <br>  वफादार निकले..   <br>   वक्त आने पर, <br>  आपका वफादार भी   <br>   कुत्ता निकल सकता है!",
    "मैंने दरवाजा खोला तो,  <br>  उसकी आँखो मे आँसू, चेहरे पर हँसी थी, <br>  साँसो मे आहे, दिल मे बेबसी थी, <br>   पगली ने पहले नही बताया की,  <br>    दरवाजे मे उसकी ऊँगली फँसी थी.",
    "सरदार लड़की वालों के यहाँ रिश्ता लेकर पहुँचा,  <br>  माँ : बाप बोले: हमारी बेटी अभी पढ़ रही है,   <br>  सरदार बोला: कोई बात नहीं जी,   <br> हम एक : दो घंटे बाद आ जायेंगे.",
    "पहला दोस्त : :  यार मैंने अपनी बहन की डायमंड    <br>  रींग चुराकर मेरी गर्लफ्रेंड को दे दी,    <br>    दुसरा दोस्त : हरामखोर, दो दिन हमाली करके खरीदकर दी थी तेरी बहन को,   <br>  पहला दोस्त : :  अबे मारता क्यों है बे साले तेरी बहन को ही तो दी है.",
    "लड़की: कितना प्यार करते हो मुझसे?    <br>  लड़का: शाहजहाँन जैसा,  <br>    लड़की: तो ताजमहल बनवाओ,    <br>    लड़का: जमीन खरीद ली है,   <br>  बस तुम्हारे मरने का इंतज़ार कर रहा हुँ.",
    "पप्पू: मेरे बाप के आगे बडे बडे लोग   <br>  कटोरी लेके खडे होते है,    <br> लड़की: अच्छा! कौन है तुम्हारा बाप? <br>   पप्पू: पानी पूरीवाला.",
    "पप्पु बहूत देर से एक लड़की को घुर रहा था, <br>  लड़की : :  तेरे घर में माँ बहन नहीं है क्या?    <br>   पप्पु : :  है न तभी तो देख रहा हुँ,    <br> क्योंकि माँ को बहू और बहन को भाभी चाहिए.",
    "दुनिया बुरी हो सकती है तुम नही,  <br>  लोग बुरे हो सकते है तुम नही,  <br>  दुनिया बेवफा हो सकती है तुम नही,    <br>  पागल ठिक हो सकते है तुम नही.",
    "एक लड़का पार्क मे पेड़ के पीछे अपनी गर्लफ्रेंड के साथ खड़ा था, <br>  एक बुढ्ढा आदमी पास से गुजरा और बोला: बेटे क्या यह हमारी संस्कृति है?  <br>   लड़का: नही अंकल, यह तो मल्होत्रा अंकल की टीना है,   <br>   आप दुसरे पेड़ के पीछे चेक कीजिए शायद वहा हो.",
    "खैरियत पूछने का जमाना गया साहिब, <br>  आदमी ऑनलाइन दिख जाये तो समझ लेना सब ठीक है..   <br>   भगवान हम सबको ऑनलाइन रखे.",
    "ज़रुरत से ज़्यादा भगवान को याद मत किया करो क्योंकि, <br>  किसी दिन भगवान ने याद कर लिया तो, <br>   लेने के देने पड़ जायेंगे.",
    "तुम ही हो मेरे आँखों के तारे, <br>  तुम ही हो मेरे जीने के सहारे,  <br>   बहुत परेशान हूँ मै मेरे यार,   <br>   उधारी के पैसे चूका दो सारे.",
    "पति : पत्नी दोनों मार्किट गए, <br>  वहा पति ने एक अनजान  <br>   लड़की से कहा हेलो!  <br>   पत्नी गुस्से में  :  बताओ ये कौन थी??  <br>   पति कुछ सोचकर  :  ओए चुप कर,    <br>   अभी उसे भी बताना है की,    <br> तुम कौन हो..!",
    "पति: :  काम के लिए बाई रखे?    <br>  पत्नी: :  नहीं चाहिए.   <br>    पति: :  क्यों?   <br>   पत्नी: :  तुम्हारी आदते मैं अच्छी तरह,  <br>  जानती हूँ. भूल गए? <br>  पहले मैं भी बाई ही थी!",
    "देवदास की तरह जान मत दो यारो, <br>  प्यार को लात मारो यारो,  <br>   मेरी बात मानो यारो,  <br>   ना चंद्रमुखी ना पारो, <br>   रोज़ रात एक किंगफ़िशर मारो,   <br>    और चैन से ज़िंदगी गुज़ारो..!",
    "गर्लफ्रेंड: मेरी मम्मी को तुम बहुत पसंद आये हो,  <br>  पप्पू: चल पगली…कुछ भी हो    <br>  मैं शादी तुमसे ही करूँगा..    <br>    आंटी से कहना वो मुझे भूल जाएँ.",
    "नज़रे आज भी उस हरामखोर को ढूँढ रही हैं,   <br>  जिसने कहा था बुक के बीच में मोर पंख रखने से विद्या आती है.",
    "ठोकर खाकर गुणगुणाना ही ज़िन्दगी है,    <br>  गम पी कर मुस्कुराना ही ज़िन्दगी है, <br>    एक लड़की अगर धोका दे दे तो सब कुछ भूल कर, <br> दूसरी को पटाना ही ज़िन्दगी है.",
    "सन: पापा, सर्कस देखने चले?   <br>  पापा: मैं बीजी हूँ.    <br> सन: पापा, उसमे एक लड़की बिना   <br>   कपड़ों के शेर पे सवारी करती है.. <br>  पापा: बहूत ज़िद्दी हो, चलो,   <br>   बहुत दिन हो गए, शेर नहीं देखा.",
    "After Falling In love: <br>  जीने लगा हूँ… पहले से ज्यादा!  <br>   After Breakup:    <br>   पीने लगा हूँ… पहले से ज्यादा !",
    "टीचर: हमेशा कहो की मुझे सब पता है.  <br>  पप्पू: पापा मुझे सब पता है.   <br>  पापा: बेटा ये ५० रुपए लो और चुप रहना.   <br> आंटी तो बस मिलने आती हैं.  <br>    पप्पू: मम्मी मुझे सब पता है.  <br>    मम्मी: बेटा ये १०० रुपए लो और चुप रहना.    <br>    रामु काका तो रूम साफ़ करते हैं बस. <br>  पप्पू (नौकर से): रामु काका मुझे सब पता है.   <br>   रामु काका: सब जान ने के बाद भी  <br>  अपने बाप के गले नहीं लगेगा पगले.",
    "भगवान को गुस्सा कब आता है?    <br>  जब .. जब कोई लड़की शादी से पहले प्रेगनेंट हो जाये..   <br>    और उसकी माँ कहे,   <br>   “हे भगवान ये तूने क्या किया”",
    "हँसी के लिए गम कुर्बान,   <br>  खुशी के लिए आँसू कुर्बान,   <br> दोस्त के लिए जान भी कुर्बान,    <br>    और, <br>  अगर दोस्त की गर्लफ्रेंड मिल जाये तो,    <br>   साला दोस्त भी कुर्बान.",
    "एक व्यक्ति नदी में डूब रहा था,  <br>  व्यक्ति: बचाओ गणेश जी बचाओ.. <br>  गणेश जी आये और नाचने लगे,  <br>   व्यक्ति: आप नाच क्यों रहे हो?  <br>   गणेश जी: तू भी मेरे विसर्जन में बोहोत नाचता है.",
    "डॉक्टर: अब क्या हाल है?  <br>  मरीज़: पहले से ज़्यादा ख़राब है. <br>  डॉक्टर: दवाई खाली थी क्या?   <br>   मरीज़: नहीं दवाई की शीशी तो <br>  भरी हुई थी. <br>   डॉक्टर: मेरा मतलब दवाई लेली थी?  <br>    मरीज़: आप ने दी तो मैंने लेली.  <br>    डॉक्टर: बेवकूफ दवाई पिली थी?  <br>    मरीज़: नहीं दवाई तो लाल थी.   <br>    डॉक्टर: गधे दवाई को पीलिया था?  <br>   मरीज़: नहीं जी पीलिया तो मुझे था.",
    "पिंकी बहुत तेजी से स्कुटी चला रही थी,   <br>  और उसने रेड लाइट क्रॉस कर दी..   <br> ट्रैफिक पुलिस: चलो स्कुटी साइड में खडी करो,  <br>    तुम्हारा चालान कटेगा. <br>    पिंकी: सर मुझे माफ कर दो This Is My First Time. <br> ट्रैफिक पुलिस: तुम्हे रेड लाइट नहीं दिखी थी क्या? <br>  पिंकी: दिखी तो थी पर आप नहीं दिखे,  <br>   न जाने कहा छुप कर बैठे थे.",
    "पति के मरने के बाद, <br>  पत्नी ने अखबार में इश्तिहार दिया.   <br>   अंतिम संस्कार में जो भी आये  <br>  उनके लिए धन्यवाद! <br>  शोकाकुल:    <br>   काजल,    <br> उम्र 26  <br>   गोरा रंग,    <br>   36 24 36,   <br> बच्चे नहीं है.",
    "कामवाली: मालकीन आपकी पुरानी <br>  साडी मुझे नहीं चाहिए.    <br>   मालकीन : क्यू?  <br> कामवाली : आपकी साडी पहनने के  <br> बाद साहब मेरे पास भी नही आते, <br> और ड्राइवर परेशान करता है.",
    "विणा अपने पति से: तुम सच मे,  <br>  बहुत सीधे साधे और भोले हो,    <br>  तुम्हे कोई भी आसानी से बेवकूफ बना सकता है.   <br>    पति: सच कह रही हो,    <br>   शुरुवात तो तुम्हारे पापा ने ही की है.",
    "पति : अगर मै मर गया तो <br>  तुम दूसरी शादी करोगी??  <br>   वाईफ : नहीं, मै अपनी बेहेन के <br>   साथ पूरी ज़िन्दगी रह लुंगी.    <br>    वाईफ : अगर मै मर गयी तो तुम  <br>  दूसरी शादी करोगे?   <br>  हसबंड : मै भी तुम्हारी बेहेन    <br> के साथ पूरी ज़िन्दगी रह लूंगा.",
    "पहला दोस्त :’ यार मै जिस लड़की को चाहता हुँ, उसने मुझसे शादी नहीं की.   <br>  दूसरा दोस्त :’ तुमने उसे बताया के तेरा चाचा करोडपती है ?    <br> पहला दोस्त :’ हाँ मेने बताया था.  <br>   दूसरा दोस्त :’ तो फिर ? <br>   पहला दोस्त :’ अब वो मेरी चाची है.",
    "आजकल दो चीज सिर्फ किस्मत वालो  <br>  को ही मिलती है..   <br>  एक तो जंगल में घुमता सफेद हाथी..!   <br> और,    <br>    दुसरा बिना अफेयर वाला जीवन साथी.",
    "बंता ने संता से पूछा : <br>  आपको एयर होस्टेस ने थप्पड़ क्यों मारा?   <br>   संता : मैंने पूछा की,  <br>  सुसु करने की जगह कहा है,    <br>  वो बोली पीछे,    <br>    मैंने कहा पहले तो आगे हुआ करती थी.",
    "पति: मरते वक़्त बीवी से:  <br>  अलमारी से तेरा गोल्ड सेट मैंने ही चोरी किया था !   <br>  बीवी रोते हुए: कोई बात नहीं जी,  <br> पति: तेरे भाई ने तुझे १ लाख अमानत दी थी, <br> वो भी मैने ग़ायब की !   <br>  बीवी: मैने आपको माफ़ किया ! <br> पति: तेरी कमेटी के पैसे भी    <br>  मैने ही चोरी किये थे!   <br>    बीवी: कोई बात नहीं जी,    <br>   आपको ज़हर भी मैंने ही दिया है.",
    "टीचर : बताओ सबसे नशीला  <br>  पदार्थ कौनसा होता है?    <br>  पप्पु : किताब है सर, <br>    साला खोलते ही नींद आ जाती है.",
    "शादी की सालगिरह पर पत्नी को गुलाब देते हुए पति बोला,   <br>  “सालगिरह मुबारक हो!”    <br> पत्नी: यह नहीं मुझे कोई सोने की चीज़ चाहिए.   <br>   पति: ओ, यह लो तकिया और आराम से सो जाओ.",
    "टीचर: बस के ड्राइवर और <br>  कंडक्टर मे क्या फर्क है??   <br>   स्टुडेंट: कंडक्टर सोया तो   <br>  किसिका टिकट नही कटेगा,    <br> ड्राइवर सोया तो, <br>   सबका टिकट कट जायेगा.",
    "लड़का  :  डिअर मेरी आँखों में देखो,  <br>  तुम्हे क्या दिख रहा है?   <br>  मुझे जल्दी से बताओ!’ <br> लड़की  : ‘सच्चा प्यार’   <br>  लड़का  : ‘oye!सच्चा प्यार की बच्ची    <br> कचरा गया है जल्दी फूंक मार.",
    "आज फिर एक सरदार ने कमाल कर दिया, <br>  एक सरदार बैंक मे आकर सो गया,   <br>   जानते हो क्यों?  <br>  बैंक के बोर्ड पे लिखा था,  <br>  सोने पे लोन मिलेगा.",
    "आपने कभी सोचा है,   <br>  की पती और चाय की पत्ती   <br> में क्या समानता है?   <br>    दोनों के नसीब में जलना और  <br>   उबालना लिखा है <br>   और वो भी औरतो के हाथ से.",
    "बच्चा मेडीकल वाले से : अंकल, गोरा करने वाली कोई क्रीम है?   <br>  मेडिकल वाला : हाँ है..    <br> शरारती बच्चा : तो साले, लगाता क्यों नहीं? <br>   रोज तेरा मुँह देखकर डर जाता हूँ !",
    "डॉक्टर : पप्पु अब तुम्हारी पत्नी कैसी है?   <br>  पप्पु : अब काफी सुधार है उसकी तबियत में,  <br> आज सुबह तो थोड़ी बहुत लड़ाई भी की उसने.",
    "२ हफ़्तों से ज्यादा खासी TB  <br>  बन जाती है.. <br>  अगर टाइम पे गर्लफ्रेंड ना   <br>   चेंज करो तो वो बीबी बन जाती है.",
    "भाईसाहब आजकल की   <br>  जनरेशन की contact लिस्ट    <br> देखकर डर ही लगता है…    <br>   ‘Mummy New’, ‘Papa 2’   <br> यह क्या है भाई?",
    "गर्लफ्रेंड: मेरी याद आती है तो तुम क्या करते हो?  <br>  बॉयफ्रेंड: तुम्हारी पसंदीदा चोकलेट खा लेता हूँ. <br>  और तुम क्या करती हो मेरी याद आये तब,  <br>   गर्लफ्रेंड: मैं भी ‘विमल’ खा लेती हु.",
    "सावधान इंडिया!  <br>  मेरे हिसाब से दुनिया मे,   <br>  सतर्क इन्सान वही है,    <br> जो टॉयलेट मे बैठने से पहले, <br>   पानी का नल चला कर देख ले,  <br>    की, पानी आ रहा है की नही.",
    "Girl : :  अपने बाल तो देखो जैसे घास उगी हो..   <br>  Boy : :  इसीलिए इतनी देर से सोच रहा हूँ के,    <br> मेरे पास भैस क्यों खड़ी है !",
    "प्यार को मत छुपाओ उसे जरुरत है जताने की,  <br>  अपनी प्रतिभाओं को मत छुपाओ उन्हें जरुरत है बढ़ाने की,  <br>  अब और परफ्यूम मत लगाओ तुम्हे जरुरत है नहाने की.",
    "तु चाँद मांग में चाँद दे दूँ,  <br>  Tu तु रात मांग में रात दे दूँ,  <br>  तु दिल मांग में दिल दे दूँ, <br>  तु प्यार मांग,    <br>   क्या यार, भिक मांगने की भी एक Limit होती है.",
    "तुम क्या जानो गम क्या होता है?   <br>  Tu तुम क्या जानो गम किसे कहते है?   <br> तुम क्या जानो गम क्या चीज होती है?    <br>    तुमने तो हमेशा Fevicol यूज किया है!",
    "दिल की बात दिल में मत रखना,   <br>  जो पसंद हो उसे ILU कहना,    <br> अगर वो गुस्से में आ जाये तो डरना मत,  <br>   राखी निकालना और कहना,   <br>   प्यारी बहना मिलती रहना.",
    "इतनी हसीन है आप,  <br>  खुद को दुनिया की नजरों से बचाया करो!  <br>  आखो में काजल लगाना काफी नहीं!   <br>  गले में लिंबु : मिर्ची भी लटकाया करो.",
    "दिल में बसी है दोस्ती तेरी,  <br>  आँखों में बसी है तस्वीर तेरी,    <br>  जब भी आती है याद तेरी,    <br>    हम देखते है,   <br>  “Tom &amp; Jerry..!”",
    "जब देखा उन्होंने <br>  तिरछी नजर से,   <br>   तो हम मदहोश हो गए.    <br>  पर जब पता चला <br>    की नजर ही तिरछी है,   <br> तो हम बेहोश हो गए !",
    "पत्नी : फ़ोन पे इतनी धीमी  <br>  आवाज़ में किस से बात कर रहे हो?    <br>  पति : बहन से..    <br>    पत्नी : तो फिर इतनी धीमी आवाज़ में किस लिए?  <br>  पति : तेरी है, इस लिए.",
    "पत्नी: शादी के दस साल हो गए और एक आप है,   <br>  जो आज तक कही घूमने तक नहीं ले गए..    <br> पति: ठीक है आज घूमने चलेंगे..   <br>   शाम को पति, पत्नी को लेकर श्मशान घाट ले गया!   <br>  पत्नी गुस्से से बोली: छी श्मशान भी कोई घूमने की जगह होती है?  <br> पति: अरे पगली लोग “मरते है” यहाँ आने के लिए.",
    "बेटा: पापा आप शराब मत पिया करो..   <br>  पापा: पिने दे बेटा, साथ क्या लेकर जाना है?   <br> बेटा: आप इसी तरह पीते रहे तो छोड़कर भी क्या जाओगे?",
    "जितना गौर से लोग,   <br>  टकराने के बाद एक दूसरे को देखते है,  <br> उतनी गौर से साले अगर पहले ही देख ले,   <br> तो टक्कर ही नहीं होती.",
    "कोई गम नहीं मगर दिल उदास है, <br>  तुझसे कोई रिश्ता नहीं फिर भी एहसास है,   <br>   कहने को बहुत अपने है मगर तू एक खास है, <br>  ज्यादा इमोशनल ना होना ऊपर सब बकवास है.",
    "मछली जल की रानी है: <br>  इसका नया वर्जन..    <br>   पत्नी घर की रानी है,  <br> करती अपनी मनमानी है,   <br> काम बताओ तो चिढ जाएगी,   <br>    शॉपिंग कराओ तो खिल जाएगी.",
    "१ युग था जब लोग अपने घर के दरवाजे पे,  <br>  लिखते थे  :  अतिथी देवो भव,    <br>  फिर लिखा  :  शुभ लाभ,  <br>    फिर लिखा  :  यू आर वेलकम,    <br>    और अब  :  कुत्तों से सावधान !",
    "अगर बीवी अपनी साडी का पल्लू    <br>  अपनी कमर में ठूस ले तो समझ जाओ की,  <br>    या तो वो घर का काम निपटाएगी,  <br>    या फिर आपको !",
    "अगर लोगों के दिल में जिंदा रहना है,    <br>  तो लोगों से पैसा उधार ले लो.",
    "प्रेमिका: तुमको पता है कल मेरा बर्थडे है?   <br>  मुझे क्या गिफ्ट दोगे?  <br> प्रेमी: जो तुम चाहो मेरी जान..  <br> प्रेमिका: रिंग? <br> प्रेमी: ठीक है रिंग दूंगा पर उठाना मत,   <br>  बैलेंस बहुत कम है.",
    "दो पंडितो में लड़ाई हो रही थी,    <br>  उन्हें लडते बहुत देर हो गयी,    <br>    तीसरा पंडित: क्या हुआ, क्यों लड़ाई कर रहे हो? <br>  एक पंडित बोला,   <br>   “जब मैं लहसुन, प्याज नहीं खाता, <br>  तो इस साले ने चिकन में डाला ही क्यों?”",
    "हमने पटाई एक लड़की तो सोचा,   <br>  हमारी लॉटरी निकल गयी,    <br> डेट पे बुलाया मिलने को तो,   <br>   हाय रे फूटी किस्मत,  <br>  वो राखी बांध के चली गयी.",
    "एक बार किसी ने पूछा की ये शादी कब होती है?  <br>  जवाब ये था की जब आपका समय अनुकूल ना हो,    <br>  राहु केतु और शनि की दशा खराब हो, <br>    आपका मंगल कमजोर हो,  <br> और भगवान ने भी आपकी मजे लेने की ठान ली हो.   <br> उस समय शादी हो जाती है!",
    "पति: काश! मैं गणपति होता, <br>  तुम रोज़ मेरी पूजा करती, मुझे लड्डू खिलाती, <br>   बड़ा मजा आता..   <br>    पत्नी: हा, काश तुम गणपति होते, मैं रोज़ लड्डू खिलाती,   <br>   और हर साल विसर्जन करके नए गणपति घर लाती,  <br>  बड़ा मजा आता..!",
    "लड़का और लड़की एक रेस्टोरेंट गए,    <br>  वेटर: म्याम, आप कुछ लेंगी? <br>    लड़की: भैया एक सब्जी वाली रोटी लाना..    <br> वेटर: क्या?    <br>   लड़का: गांव से आयी है, पिज्जा वाली रोटी मांग रही है.",
    "हम तो ऐसे ही उदासी में बैठे : बैठे, <br>  पानी में पत्थर मार रहे थे,   <br>   अचानक से एक मेंढक निकला और बोला,   <br>  पानी में तो आ, तेरी उदासी उतारू साले..  <br> तेरी वाली के चक्कर में तूने,    <br> मेरी वाली का सर फोड़ दिया.",
    "सांता: डॉक्टर साहब, प्लास्टिक सर्जरी में कितना खर्चा आएगा?    <br>  डॉक्टर: ५० हजार    <br>    सांता: अगर प्लास्टिक मैं लेकर दूँ तो?    <br>  डॉक्टर: साले, पिघला कर चिपका भी लेना.",
    "शिक्षक: तुमने आज भी होमवर्क नहीं किया..   <br>  बोलो तुम्हे क्या सजा दूँ?    <br> पप्पू: सर वो लास्ट बेंच वाली लड़की ने भी,    <br>   होमवर्क नहीं किया.    <br> “हम दोनों को बाथरूम में बंद कर दो”",
    "एक सफल आदमी वो है जो अपनी   <br>  बीवी के खर्च से ज्यादा कमा सके.. <br> एक सफल औरत वो होती है जो ऐसा   <br>  आदमी खोज सके.",
    "पापा: दिन भर फेसबुक पर बैठा रहता है,    <br>  ये तुझे रोटी नहीं देने वाली,   <br>    बेटा: पापा मुझे भी पता है रोटी नहीं देगी, <br>   पर रोटी बनाने वाली तो यही मिलेगी!",
    "शादी करनी हो तो,    <br>  अपनी गर्लफ्रेंड से करो..   <br>    दूसरों की गर्लफ्रेंड से तो,  <br>   घरवाले भी करवा देते है.",
    "माँ अपने बेटे से: उठ जा कम्बखत,    <br>  देख सूरज कब का निकल आया है,   <br>    बेटा अपनी माँ से: तो क्या हुआ माँ! <br>   वो सोता भी तो मुझसे पहले है.",
    "पत्नी : ‘RAEES’ देखने चले?  <br>  पति : मैं उस ‘KAABIL’ नहीं..   <br>  पत्नी : तो ‘KAABIL’ चले?   <br> पति : मैं उतना ‘RAEES’ नहीं..    <br>    बाद में घर में बच्चों ने ‘DANGAL’ देखा.",
    "प्यार और “11:59pm” में क्या फर्क है?   <br>  Confused ? <br> Simple! दोनों के बाद १२ बजते है,    <br>  और दिन बदल जाते है.",
    "सांता के ९ बेटो में १ अलग दिखता था,   <br>  सांता ने मरते वक़्त बीवी से पूछा,  <br> अब तो सच बता ये अलग दिखने वाला किसका है?    <br> बीवी  :  ये १ ही तो आपका है !",
    "सर : बच्चो, गरीबो से हमेशा प्यार से पेश आना चाहिए..  <br>  लड़का : अब समझा..    <br>  सर : क्या?    <br>    लड़का : तभी पापा नौकरानी को गले लगाते है और मम्मी दूधवाले को !",
    "पहला सरदार : मैंने अपनी वाईफ को १२ वी पास करवाई,  <br>  फिर, बी. ए, .फिर एम .ए,  <br>  और उसकी सरकारी जॉब लगवा दी, <br>  अब क्या करू?    <br>   दूसरा सरदार : अच्छा लड़का देख कर शादी कर दे !",
    "सरदार ट्रैन कि पटरी पर सो गया,    <br>  एक आदमी बोला ट्रैन आएगी तो मर जायेगा, <br>    सरदार  :  साले, अभी प्लेन ऊपर से गया, कुछ नहीं हुआ…    <br> तो ट्रैन क्या चीज़ है?",
    "लड़का : यार, मुझे उस लड़की से बचाओ, <br>  दोस्त : क्यों?    <br>   लड़का : जब से मैंने कह दिया है दिल चीर के देख तेरा ही नाम होगा,    <br> साली ‘चाकू’ लेके पीछे पड़ गयी है !",
    "गधा: यार मालिक बहुत मारते है?  <br>  कुत्ता: घर छोड़ दे? <br>  गधा: नही यार! वो हमेशा बेटी से बोलता है, <br>   तेरी शादी गधे से कर दुंगा.    <br>    बस इसी उम्मीद में बैठा हु !",
    "१ छोटा बच्चा रोड पर पोट्टी कर रहा था,    <br>  पुलिस ने उसे पकड़ लिया,    <br>    जब उसे ले जाने लगे तो बच्चा बोला, <br>  ओ कानून के रखवालो,    <br>   सबूत तो ऊठा लो.",
    "किसी लड़की को छेड़ो,   <br>  ऊसका हाथ पकड़ो,    <br> अगर वो थप्पड़ मारे,  <br>   तो कहो :    <br>   तुम पहले इम्तिहान में पास हो गई. <br> मुझे ऐसी ही शरीफ लड़की चाहिए थी !",
    "प्रेमी अपने.   <br>  प्रेमिका की ज़ुल्फ़ों में ऐसा खोया.    <br> की, बेहोश हो गया..   <br>   जब होश में आया तो रोमांटिक हो कर पूछा, <br>  जानु ! नहाती नहीं हो क्या ?",
    "टीचर : ‘लोफर’ और ‘ऑफर’ में क्या अंतर है.?  <br>  स्टूडेंट : सिंपल मॅम.    <br>  लड़का ‘I Love U’ बोले तो लोफर <br>    और, लड़की ‘I Love U’ बोले तो ऑफर!",
    "सरदार ने सर्दी मे AC लगवाया,  <br>  किसीने पूछा: इतनी सर्दी मे AC? <br>  सरदार : ओये मैंने उल्टा लगवाया,   <br>   गरम हवा अंदर और ठंडी हवा बाहर जायेगी!",
    "आदमी भगवान से : ज़मीन से आसमान तक रोड बना दो,    <br>  भगवान : असंभव कुछ और मांगो    <br>    आदमी : वाईफ को आज्ञाकारी और अकल्मन्द बना दो!   <br>  भगवान : रोड सिंगल बनाउ या डबल?",
    "पिताजी : बेटा, मेरे लिए १ ग्लास पानी लाना,   <br>  लड़का : नहीं लाऊंगा,  <br> दूसरा लड़का : रहने दो पापा, ये तो है ही बत्तमीज,    <br> आप खुद लेलो, और मेरे लिए भी १ ग्लास ले आना !",
    "एक लड़की : हे भगवान, मेरी शादी किसी समझदार आदमी से करवा दो,   <br>  भगवान : घर जाओ बेटी समझदार आदमी कभी शादी नहीं करते !",
    "सांता  :  आज तेरे मोबाइल पे बड़े “I LOVE U” के मैसेज आ रहे है,  <br>  क्या बात है?  <br>  बंता  :  ओ कुछ नही यार, अपनी ऐसी किस्मत कहा,  <br>  आज तो बीवी का मोबाइल लाया हु !",
    "एक लड़का फ़ैल हुआ उसके पापा ने कहा,  <br>  देख : देख उस लड़की को देख,    <br>  वो तुम्हारे साथ पढ़ती है और 1st आयी है.    <br>    लड़का: देख देख क्या देख,   <br>  उसीको देख देख के तो फ़ैल हुआ हूँ !",
    "लड़की  :  अगर मै मर जाऊ तो तुम क्या करोगे? <br>  लड़का  :  मै भी मर जाऊंगा,    <br>   लड़की  :  पर क्यों?    <br> लड़का  :  कभी कभी ज्यादा ख़ुशी भी जान ले लेती है !",
    "फेकू :  पप्पू, जल्दी से टीवी चालू कर, 30 फीट का सांप दिखा रहे हैं    <br>  पप्पू :  अरे फेकू, नहीं देख सकते हम    <br>    फेकू :  क्यों? <br>  पप्पू :  क्योंकि हमारा टीवी 21 इंच का है ना.",
    "लड़की  :  परसो मै तुम्हे राखी बांधने आयी थी,   <br>  पर तुमने नहीं बंधवाई क्यू? <br> लड़का  :  अगर में तेरे लिए मंगलसूत्र लाऊ  <br>  तो क्या बंधवायेगी, बात करती है.",
    "बेटा  :  मुझे शादी नहीं करनी! मुझे सभी औरतों से डर लगता है!   <br>  पिता :  कर ले बेटा! फिर एक ही औरत से डर लगेगा, बाकी सब अच्छी लगेंगी.",
    "बंता : तेरे घर से हमेशा हसने कि आवाज़ आती हे,   <br>  इतनी खुशी का राज़ क्या हे?  <br> संता : मेरी बीवी मुझे जूते मारती हे,   <br> लग जाये तो वो हसती हे,   <br>    नही लगे तो में हसता हु !",
    "१ बार गांधी जी के सर पे ८ : १० बाल आये,   <br>  वो बार्बर के पास गए,    <br> बार्बर ने गुस्से से पूछा कट करू या काउंट करू? <br>   बापू नम्रता से बोले कलर इट डूड.",
    "मैंने सुना है    <br>  आप बहुत कमज़ोर हो गए हो, <br>    फिट रहने के लिए  <br> रोज़ १ चम्मच खाया करो अंबुजा सिमेंट   <br> क्यों के, इस सिमेंट में जान है !",
    "पत्नी :  शादी से पहले तुम मुझे होटल,   <br>  सिनेमा, और न जाने कहां :  कहां घुमाते थे  <br> शादी हुई तो घर के बाहर भी नहीं ले जाते..  <br> पति :  क्या तुमने कभी किसी को..  <br> चुनाव के बाद प्रचार करते देखा है.",
    "कभी हाथ पे, कभी होंट पे,  <br>  Ka कभी आँख पे,कभी गाल पे,   <br>  कभी नाक पे,   <br> Kiss क़दर मक्खियाँ तंग करती है,    <br>    बरसात में.",
    "मास्टर जी : अगर पृथ्वी के अंदर LAVA है तो बाहर क्या है ? <br>  संजू : मास्टर जी बाहर ओप्पो और VIVO है.",
    "सर : अंग्रेज़ो ने चाँद पर पानी   <br>  और बरफ की खोज कर ली है.    <br> बताओ इससे तुमने क्या सिखा?  <br>   सांता : बस हमे अब सिर्फ दारु  <br>   और नमकीन लेके जाना है !",
    "हसबंड वाईफ मे लडाई हुई, <br>  Has हसबंड घर से चला गया, <br>   हसबंड: रात को फोन पे,”खाने मे क्या है”  <br>    वाईफ: ज़ेहर. <br>    हसबंड: मै देर से आऊँगा,तुम खा कर सो जाना.",
    "टीचर: :  सेमिस्टर सिस्टम के फायदे बताओ?    <br>  स्टूडेंट: :  फायदे तो पता नहीं, <br>    पर बेइजत्ती साल में २ बार हो जाती है.",
    "भिकारी :  कुछ खाने को दे दो,  <br>  लडकी :  टमाटर खाओ, <br>  भिकारी :  रोटी दे दो, <br>   लडकी :  टमाटर खाओ,    <br>    भिकारी :  अच्छा लाओ टमाटर ही दे दो, <br>  लडकी की माँ :  अरे तुम जाओ बाबा…ये तोतली है.    <br>   कह रही है..कमा कर खाओ.",
    "जिस लौंडे कि शादी, उसकी पहली ही गर्लफ्रेंड से हो जाए तो ऐसा लगता है <br>  जैसे बंदा “Try Ball” पर ही आउट हो गया.",
    "लड़की : प्लीज़ मेरे हसबंड को अंदर बुला लीजिये,    <br>  डॉक्टर : घबराओ नही मै एक शरीफ आदमी हुँ.  <br>    लड़की : आप समझे नही, बाहर आपकी नर्स अकेली है.",
    "बिपाशा को लड़का हुआ ‘काला’  <br>  जॉन बोला : तू गोरी में गोरा फिर लड़का क्यू ‘काला’  <br>  बिपाशा बोली : तू ‘हॉट’ मै ‘हॉट’ लड़का जल गया ‘साला’",
    "गवर्न्मेंट का नया रूल.    <br>  जिसके 5 बच्चे हो उसे घर मिलेगा.  <br>    पप्पू के 3 थे उसने वाईफ से कहा,   <br>    पड़ोस के 2 मेरे है उनको लेके आता हूँ ! <br>   ( लाने के बाद )  <br>    पप्पू : अपने 3 कहा गए?    <br>    वाईफ : जिसके थे वह ले गया.",
    "वाईफ: जानू हम ना.. <br>  मंडे .. शॉपिंग    <br>   ट्यूसडे .. होटल <br> वेडनेसडे .. आउटिंग    <br>  थर्सडे .. डिनर <br>    फ्राइडे .. मूवी   <br> सैटरडे .. पिकनिक जायेंगे.  <br>    कितना मज़ा आएगा ना. <br>    हसबंड: येस, और संडे मंदिर..    <br> वाइफ: क्यों..?  <br>   हसबंड: “भीक मांगने”",
    "वाईफ: :  अगर मै माउंट एवरेस्ट  <br>  पर चढ़ूँ तो आप मुझे क्या दोगे?  <br>  हसबंड: :  पगली,   <br>  इसमें पूछने वाली क्या बात है.    <br> “धक्का”",
    "अमीर आदमी: आज मेरे पास 14 कार,18 बाइक्स, 4 बंगले, 3 फार्महाउस है,    <br>  तुम्हारे पास क्या है?   <br>    गरीब आदमी: मेरे पास बेटा है,   <br>   जिसकी गर्लफ्रेंड तेरी बेटी है.",
    "पत्नी: शरम नही आती, दुसरी    <br>  औरत को घुर घुर कर देख रहे हो! <br>    अब तुम शादी शुदा हो.   <br> पती: ऐसा कहा लिखा है की उपवास  <br>    हो तो खाने का मेनू भी नही देख सकते.",
    "मुकेश अंबानी: अगर मै सुबह से   <br>  अपनी कार में निकलू तो शाम तक   <br> अपनी आधी प्रॉपर्टी भी नही देख सकता,  <br>    संता: हमारे पास भी ऐसी ही खटारा कार थी,   <br>    बेच दी.",
    "सरदार अपनी बीवी के साथ टॅक्सी मे बैठा, <br>  ड्राइवर ने आईना सेट किया,   <br>   ये देखते ही सरदार: ( गुस्से मे ) साले मेरी बीवी को देखता है,  <br>  तु पीछे बैठ टॅक्सी मे चलाऊंगा !",
    "मालकीन रो रही थी,   <br>  तभी जाकर नौकरानी ने पुछा,  <br> नौकरानी: क्या हुआ मालकीन? <br> मालकीन: मुझे शक है की तेरे मालिक का <br>  ऑफिस मे किसी दूसरे लडकी के साथ चक्कर है.    <br>   नौकरानी: नही मालकीन, ऎसा मत सोचिए,   <br> मालिक मुझे धोका नही दे सकते !",
    "लड़का : कल से हम कही और मिलंगे    <br>  लड़की : क्यू?   <br>    लड़का : बड़े कमीने है तेरी गली के बच्चे <br>   लड़की  :  क्या हुआ? <br>    लड़का : कुत्ते पीछे लगाकर कहते है, <br> जब प्यार किया तो डरना क्या !",
    "एक मक्खी गंजे के सर पर बैठी थी,    <br>  दुसरी ने कहा वाह.!   <br>    क्या घर मिला है तुझे. <br>   पहिली मक्खी : नही रे, अभी   <br>    तो सिर्फ प्लॉट खरीदा है..!",
    "अपना बच्चा रोये तो दिल मे दर्द होता है,    <br>  और दुसरे का रोये तो सिर मे. <br>    अपनी बीवी रोये तो सिर मे दर्द होता है,   <br> और दुसरे की रोये तो दिल मे.",
    "पूरी शराब की बोतल ही गटक ली आज उसने.   <br>  बीवी ने तो सिर्फ इतना ही कहा था के आज ‘PK‘ दिखा दो.",
    "एक आदमी राम मंदिर गया और रोने लगा, <br>  हे राम मेरी बिवी खो गयी, <br>   राम जी बोले, <br>    बाजूवाले हनुमान मंदिर मे जाके बोल,   <br> मेरी भी उसी ने धुंडी थी.",
    "सरदारजी आपको लोगो ने क्यो मारा?  <br>  सरदार: यार मेरी फोटो बस मे गिर गयी,    <br>  तो मैने मैडम से कहा जरा साडी उपर करो फोटो लेना है.",
    "मेरी बात गौर से सुनना,    <br>  अगर कोई आपको पागल कहे तो दुखी  <br>    मत होना, अफ़सोस भी मत करना और   <br>    रोना भी मत, बस आराम से चेयर  <br>   पर बैठ कर सोचना की.   <br>   साले को पता कैसे चला.",
    "यह जो हसीनाओं के बाल होते है,   <br>  लड़को को फ़साने के जाल होते है,   <br> पी जाती है सारा खून लड़को का,    <br>    तभी तो गाल इतने लाल होते हैं..",
    "लेडी टीचर: मुझे बच्चों की   <br>  शकल से पता लग जाता है की <br> उनके दिमाग मे क्या चल रहा है.    <br>  स्टूडंट : फिर भी आप अपना  <br>    दुपट्टा सही नहीं कर रही हो!",
    "लड़की : दुआ करो मैं फ़ैल हो जाऊं. <br>  फ्रेंड : क्यों?    <br>   लड़की : अब्बु ने कहा है के. <br> 1st आयी तो लैपटॉप.   <br>  2nd आयी तो मोबाइल और फ़ैल हो  <br> गयी तो शादी करवा दूँगा!",
    "बेटा: माँ हम दिवाली के सारे  <br>  पटाखे इस दूकान से लेंगे.. <br>  माँ: बेटा ये दूकान नहीं   <br>   गर्ल्स हॉस्टल है..  <br>  बॉय: पर पापा तो कहते है <br>  यहाँ एक से एक पटाखे है !",
    "भिकारी: साहब एक रुपया दे दो.   <br>  साहब: तुम्हे शरम नही,   <br> रोड पर खडे होकर भीक मांगते हो, <br>    भिकारी: अब तुझे एक रूपये मांगने के लिए   <br> ऑफिस खोलु क्या?",
    "साइकिल चलाकर पैर दुखे तो बाईक ली,   <br>  बाईक चलाकर पीठ दुखी तो कार लाये,    <br> कार चलाकर पेट निकला तो जिम ज्वाइन किया और  <br>   जिम में वापस साइकिल,    <br>   इसे कहते है रिसायक्लिंग.",
    "लडका फोन पे अपने दोस्त को:    <br>  क्या बे कुत्ते के पिल्ले, <br>    आया क्यों नही..?  <br> जबाब आया: कुत्ते का पिल्ला नहाने गया है,   <br> मैं कुत्ता बोल रहा हूँ..    <br>    ​लडका: सॉरी अंकल.",
    "पत्नी : आप मुझे “रानी” क्यों बोलते हो? <br>  पति : क्योंकि “नौकरानी” थोडा लम्बा शब्द हो जाता है..  <br>   पत्नी गुस्से से: तुम्हे पता है कि मै तुम्हे “जान” क्यों बोलती हूँ?    <br>   पति : नहीं.. बताओ तो जरा..    <br> पत्नी : “जानवर” थोडा लम्बा शब्द हो जाता है इसलिए सिर्फ “जान” बोल देती हूँ.",
    "एक नई शादीशुदा औरत कोक पी रही थी,  <br>  उसमे एक मच्छर गिर गया,    <br>  औरत ने उसे निकाला तो मच्छर बोला, “माँ!”    <br>    औरत: तूने मुझे माँ क्यों कहा? <br>  मच्छर: मैं तेरी कोक से निकला हूँ, माँ!",
    "5 साल का बच्चा: आई लव यू माँ, <br>  माँ: आई लव यू टू बेटा! <br>   16 साल का लड़का: आई लव यू मॉम, <br>    माँ: सॉरी बेटा, पैसे नही है!   <br> 25 साल का लड़का: आई लव यू माँ,    <br>    माँ: कौन है वो चुड़ैल? कहा रहती है?    <br>  35 साल का आदमी: आई लव यू माँ, <br>    माँ: बेटा मैंने पहले ही बोला था, उस लड़की से शादी मत करना! <br> और सबसे बढ़िया.. <br>  55 साल का आदमी: आई लव यू माँ,  <br>   माँ: बेटा, मै किसी भी कागज़ पर साइन नहीं करूंगी !",
    "फ्रेंड: यार तुम्हारी दुकान मिठाई की है,  <br>  तो क्या तुम्हारा दिल नहीं करता,  <br>  मिठाई खाने को? <br>  सांता: यार करता तो बहोत है,  <br>   लेकिन पापा रसगुल्ले गिन के जाते है,   <br>   तो.. इसलिए,चूसकर रख देता हु.",
    "मोहब्बत के खर्चों की बड़ी लंबी कहानी है, <br>  कभी फिल्म दिखानी है तो कभी शॉपिंग करानी है, <br>   मास्टरजी रोज कहते है कहाँ है फीस के पैसे? <br>    उसे समजाऊँ मैं कैसे की मुझे छोरी पटानी है !",
    "तेरी दुनिया में कोई गम न हो,    <br>  तेरी खुशियाँ कभी कम न हो,   <br>    भगवान तुझे ऐसी आईटम दे, <br>   जो सनी लिओनी से कम न हो !",
    "आज मैने अपनी Wife के फोटो पर कमेन्ट किया,    <br>  CUTEEE. <br>    Wife ने मुझे कॉल करके 100 गालियॉ दी.. <br> मैँने पुछा आखिर मैँने किया क्या है ?   <br>  Wife: तूने “कुत्ती” क्यूँ बोला..?    <br> कसम से यार रोना आ गया.. पता नही कहा से पढाई की है.",
    "मैं बचपन से इतना प्रतिभाशाली रहा हूँ कि <br>  रिश्तेदार परीक्षा परिणाम के बाद सिर्फ इतना ही पूछते है,    <br>   तू पास हुआ या नहीं ?",
    "जिन्दगी की बात करते हो,   <br>  यहाँ तो मौत भी हम से खफा है,   <br> हम ताज क्यों बनाए,  <br>    अपनी तो मुमताज ही बेवफा है.",
    "अर्ज किया है,  <br>  फिजा मे महकती शाम हो तुम,    <br>  प्यार का पहला जाम हो तुम,  <br>    और क्या कहे जानम तुम्हारे बारे मे,   <br>    खर्चे का दूसरा नाम हो तुम..",
    "हम हमेशा दो लोगों के लिए अगरबत्ती लगाते है, <br>  एक भगवान के लिए, उन्हें बुलाने के लिए.. <br>   और दूसरी अगरबत्ती मच्छर के लिए, <br>    उन्हें भगाने के लिए..   <br> पर होता उसके बिलकुल उलटा है.. <br>    भगवान आते नहीं है और, <br> मच्छर है कि जाते नहीं है.",
    "गब्बर: आज मैने बसंती को नहाते वक्त देखा.. <br>  वीरू: कुत्ते कमीने.. मैं तेरा खून पि जाऊँगा! <br>   गब्बर: रिलॅक्स बेवडे.. मैं नहा रहा था.. <br>    बसंती जा रही थी.. <br> जब देखो तब खून पि जाऊँगा.",
    "डॉक्टर: अब आप खतरे से बाहर है,   <br>  फिर भी आप इतना क्यों डर रहे हो?    <br> मरीज: जिस ट्रक से मेरी दुर्घटना हुई थी,    <br>   उसपे लिखा था, “फिर मिलेंगे”",
    "डॉक्टर : जब आपको पता था,    <br>  छिपकली आपके नाक मे जा रही है,   <br>    तो आपने रोका क्यों नही?    <br>   पेशंट: पहले कॉकरोच गया था, <br> मैंने सोचा उसे पकडने जा रही होगी.",
    "वाईफ: सुबह मेरे चेहरे पे पानी क्यों डाला?    <br>  हसबंड: तेरे बाप ने कहा था, <br>    “मेरी बेटी फुल की  <br> तरह है ईसे मुरझाने मत देना”.",
    "पप्पू का इंटरव्यू:   <br>  बताओ वो कौन सी औरत <br> हैं जिसको 1oo% पता होता हैं   <br>  की उसका हसबंड कहा हैं?   <br> पप्पू ने अपना खतरनाक दिमाग लगाया और बोला, <br>    “विधवा औरत”",
    "पापा: नालायक, तुमने अपनी मम्मी से    <br>  ऊँची आवाज़ मे बात क्यों की?   <br>    बेटा: मुझे पता है पापा <br>   आपको जलन हो रही है   <br>    क्यों के,  <br>   आप ऐसा नही कर सकते.",
    "सरदार ट्रेन मे सुसू करने गया,  <br>  वाईफ: आपका पैंट गिला कैसे हुआ? <br>  सरदार: वहा लिखा था, कृपया शरीर का कोई अंग बाहर ना निकाले.",
    "बेटा  :  पापा आप रातको मम्मी के साथ क्यू सोते हो?   <br>  पापा  :  बेटा इससे आपस में प्यार बढ़ता हे,   <br> बेटा  :  पापा उल्लू मत बनाओ,    <br>    साथ सोने से प्यार नही परिवार बढ़ता है.",
    "२ दोस्त सालो के बाद मिले,  <br>  पता चला दोनों कि शादी हो गयी,   <br>  पहला दोस्त: कैसी हे तुम्हारी वाईफ?    <br> दूसरा दोस्त: स्वर्ग की अप्सरा है, और तेरी?  <br>   पहला दोस्त: मेरी तो अभी ज़िंदा हे !",
    "टीचर: इतने दिन से कहा थें?    <br>  लड़का : बर्ड फ्लू हुआ था,  <br>    टीचर: पर ये तो बर्ड्स को होता है?  <br>    लड़का : आपने मुझे इंसान समझा ही कहा है, रोज़ तो मुर्गा बना देती हो.",
    "एक बार भगवान् ने एक आदमी से सवाल किया “तेरी ईच्छा क्या है” <br>  आदमी बोला “प्लीज मुझे मेरे कॉलेज के दिन वापस दे दो”  <br>   भगवान हसने लगे और कहा “मन्नत मांगने को कहा था जन्नत नहीं !",
    "आदमी: सर, मेरी वाइफ घूम गई हे,   <br>  पोस्टमन: यह पोस्ट ऑफिस है, पुलिस स्टेशन नहीं,  <br> आदमी: ओह सॉरी ! साला ख़ुशी के मारे कहा जाऊ, कुछ समझ में नहीं आ रहा !",
    "बाप  :  बेटा अगर ससुराल वाले    <br>  स्कूटर दे तो कार मांगना,    <br>    कूलर दे तो AC मांगना, <br>  लड़का  :  पापा अगर वो लड़की दे तो उसकी माँ को भी माँगलू क्या?",
    "लड़कियो को गाली मत दो,    <br>  बस एक वर्ड काफी है, <br>    जो गाली से ज्यादा असर करदेगा..    <br> और वो है, आंटी जी.",
    "टीचर ने गधे के सामने 1   <br>  दारु की और 1 पानी की बाल्टी <br> रखी, गधा पानी पी गया.  <br>  टीचर: तुमने इस से क्या सिखा?  <br>  स्टूडेंट : जो दारु नहीं पिता <br>  वह गधा होता है !",
    "दूल्हा रोमांटिक अंदाज़ में बोला, <br>  मैं आपकी kiss ले लु क्या?   <br>   दुल्हन शरमाते हुए बोली,   <br>  हमने तो कभी गैरो को भी    <br> मना नहीं किया,   <br>   आप तो फिर भी अपने हो.",
    "एक आदमी मेडिकल शॉप पर  <br>  ज़हर लेने गया.    <br>  आदमी: एक ज़हर की बोतल देना    <br>    दुकानदार: बिना पर्ची के <br>  ज़हर नहीं मिल सकता.   <br>   आदमी ने शादी का कार्ड दिखाया..   <br>  दुकानदार: बस कर पगले, रुलाएगा क्या? <br> बड़ी बोतल दू या छोटी?",
    "एक फैमिली शोले फिल्म देख   <br>  कर अपने घर आयी.  <br> तभी पति ने पत्नी से,    <br> रोमांटिक अंदाज़ में कहा,  <br>   नाच बसंती नाच..   <br>   तभी उनका छोटा बच्चा बोला,  <br>  नहीं मम्मी ईस कुत्ते के सामने मत नाचना..!",
    "हमको यु पागल बनाना छोड दो,    <br>  बेवजह हर बात पे सताना छोड दो,  <br>    तुम्हारी खुशबू अलग ही होती है मेरे दोस्त,   <br>    बर्तन वाले साबुन से नहाना छोड दो.",
    "अकबर : मुझसे वादा कर तेरी बीवी की पहली किस मुझे लेने देगा,  <br>  बीरबल : वादा हुजूर! पर मेरी भी एक शर्त है,  <br>  अकबर : बोल?    <br>  बीरबल : शादी आपकी बहन से करूंगा.",
]



let hinbtn = document.querySelector('#hindi')
let engbtn = document.querySelector('#english')
let date = new Date().getUTCFullYear()
document.getElementById('currentYear').innerText = date
hinbtn.addEventListener('click', () => {
    let hindijoke = hindi[Math.floor(Math.random() * hindi.length)];
    let div = document.getElementById("change")
    div.innerHTML = `<h5>${hindijoke}</h5>`;
});
engbtn.addEventListener('click', () => {
    let englishjoke = myjoke[Math.floor(Math.random() * myjoke.length)];
    let div = document.getElementById("change")
    div.innerHTML = `<h5>${englishjoke}</h5>`;
});


